name: "Terraform Plan"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  tf_actions_working_dir: "./terraform"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
      
      - run: pwd
      - run: terraform init
